import google.generativeai as genai

YOUR_API_KEY="AIzaSyDbTLapLT1Bxdsld7atQXG9YOtpfzPCsqE"

def generate_suggestions_function(event_title):
    """
    Generate concise description suggestions for an event based on its title.

    Args:
        event_title: The title of the event (string).

    Returns:
        A list of concise description suggestions generated by Gemini (strings).
    """

    # Replace 'YOUR_API_KEY' with your actual API key
    genai.configure(api_key=YOUR_API_KEY)

    # Craft concise prompts for event descriptions
    prompts = [
        f"Write a concise description for the event titled '{event_title}' in a captivating way.",
    ]

    max_suggestions = 2  # Adjust the number of suggestions as needed
    suggestions = []

    for prompt in prompts:
        # Send the request to Gemini using the 'gemini-1.5-flash' model
        response = genai.GenerativeModel('gemini-1.5-flash').generate_content(prompt)

        # Extract and append the generated suggestion
        suggestions.append(response.text)
    
        # Limit the number of suggestions
        if len(suggestions) >= max_suggestions:
            break

    return suggestions
