# Generated by Django 3.0.7 on 2024-07-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_auto_20240702_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=10),
        ),
    ]
